name: Docker image publish

on:   
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - main
      - cleaningmodule
      - dockerimg

env:
  IMAGE_NAME: mujbot

jobs:
  # Push image to GitHub Packages.
  # See also https://docs.docker.com/docker-hub/builds/
  push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v3

      - name: Build image
        run: docker build . --file Dockerfile --tag ghcr.io/hedgezi/$IMAGE_NAME:${GITHUB_RUN_ID}

      - name: Log in to registry
        # This is where you will update the PAT to GITHUB_TOKEN
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin

      - name: Push image
        run: |
          docker push ghcr.io/hedgezi/$IMAGE_NAME:${GITHUB_RUN_ID}

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/staging.key
          chmod 600 ~/.ssh/staging.key
          cat >>~/.ssh/config <<END
          Host staging
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/staging.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST }}

      - name: Check SSH connection
        run: ssh staging 'whoami'

      - name: Pull docker-image
        run: ssh staging "docker pull ghcr.io/hedgezi/$IMAGE_NAME:${GITHUB_RUN_ID}"

      - name: Stop docker container
        if: always()
        run: ssh staging 'docker stop mujbot'

      - name: Delete docker container
        if: always()
        run: ssh staging 'docker rm mujbot'

      - name: Start docker container
        if: always()
        run: ssh staging "docker run -d --name mujbot -v /home/${{ secrets.SSH_USER }}/homecontroltgbot/states.json:/app/states.json -v /home/${{ secrets.SSH_USER }}/homecontroltgbot/configs.py:/app/configs.py -v /home/${{ secrets.SSH_USER }}/homecontroltgbot/moneyreport.py:/app/moneyreport.py ghcr.io/hedgezi/$IMAGE_NAME:${GITHUB_RUN_ID}"